In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

Load datasets

In [2]:
X, Y = [], []

In [3]:
# 40 records
xs0 = np.loadtxt('40ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('40ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('40ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('40ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 10
ys.extend([1] * 10)
ys.extend([2] * 10)
ys.extend([3] * 10)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

In [4]:
# 400 records
xs0 = np.loadtxt('400ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('400ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('400ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('400ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 100
ys.extend([1] * 100)
ys.extend([2] * 100)
ys.extend([3] * 100)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

In [5]:
# 800 records
xs0 = np.loadtxt('800ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('800ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('800ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('800ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 200
ys.extend([1] * 200)
ys.extend([2] * 200)
ys.extend([3] * 200)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

In [6]:
# 1600 records
xs0 = np.loadtxt('1600ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('1600ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('1600ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('1600ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 400
ys.extend([1] * 400)
ys.extend([2] * 400)
ys.extend([3] * 400)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

In [7]:
# 3200 records
xs0 = np.loadtxt('3200ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('3200ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('3200ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('3200ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 800
ys.extend([1] * 800)
ys.extend([2] * 800)
ys.extend([3] * 800)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

In [8]:
# 4000 records
xs0 = np.loadtxt('4000ARs/M_Car1_aug_shs0.txt')
xs1 = np.loadtxt('4000ARs/M_Car1_aug_shs1.txt')
xs2 = np.loadtxt('4000ARs/M_Car1_aug_shs2.txt')
xs3 = np.loadtxt('4000ARs/M_Car1_aug_shs3.txt')
xs = np.append(xs0, xs1, axis=0)
xs = np.append(xs, xs2, axis=0)
xs = np.append(xs, xs3, axis=0)

ys = [0] * 1000
ys.extend([1] * 1000)
ys.extend([2] * 1000)
ys.extend([3] * 1000)
ys = np.array(ys)

X.append(xs)
Y.append(ys)

Train classifiers

In [9]:
n_es = [5, 10, 20, 50, 100]
sample_split = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

for n_estimators in n_es:
    accs = []
    print "Number of trees ::", n_estimators
    print
    for train_size in sample_split:
        train_acc, test_acc = [], []
        for xs, ys in zip(X, Y):
            train_x, test_x, train_y, test_y = train_test_split(xs, ys, train_size=train_size)
            clf = RandomForestClassifier(n_estimators = n_estimators)
            clf.fit(train_x, train_y)
            train_acc.append(accuracy_score(train_y, clf.predict(train_x)))
            test_acc.append(accuracy_score(test_y, clf.predict(test_x)))
        # print "Sample split :: {}% / {}%".format(100 * train_size, 100 * (1 - train_size))
        # print train_acc
        # print test_acc
        # plt.plot(train_acc)
        # plt.plot(test_acc)
        # plt.show()
        accs.append(test_acc)
    print np.matrix(accs)
    print

Number of trees :: 5



C:\ProgramData\Anaconda2\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


[[ 0.15625     0.246875    0.3         0.30546875  0.39765625  0.4490625 ]
 [ 0.28571429  0.30714286  0.2875      0.37142857  0.43883929  0.49071429]
 [ 0.08333333  0.2875      0.33958333  0.353125    0.47708333  0.52375   ]
 [ 0.25        0.235       0.3475      0.3575      0.535       0.573     ]
 [ 0.25        0.34375     0.3625      0.3546875   0.5328125   0.611875  ]
 [ 0.16666667  0.275       0.35416667  0.41041667  0.54479167  0.61583333]
 [ 0.25        0.375       0.3625      0.4         0.571875    0.59875   ]]

Number of trees :: 10

[[ 0.125       0.296875    0.3421875   0.32734375  0.47734375  0.4909375 ]
 [ 0.25        0.27857143  0.37142857  0.39464286  0.5         0.58857143]
 [ 0.08333333  0.25833333  0.39791667  0.43125     0.57708333  0.63041667]
 [ 0.3         0.275       0.3475      0.46        0.585       0.669     ]
 [ 0.0625      0.29375     0.39375     0.4671875   0.60234375  0.69125   ]
 [ 0.16666667  0.28333333  0.4125      0.48125     0.659375    0.725     ]
